import java.awt.*; 
import javax.swing.*;
import java.util.ArrayList;
import java.util.Arrays;


/**
 *
 * @author kyley
 */
public class ReversiBoard extends javax.swing.JFrame {

    /**
     * Creates new form ReversiBoard
     */
    public ReversiBoard() {
        initComponents();
    }
    
    public static int[][] arrayBoard = new int[8][8];
    public static JButton[][] boardList = new JButton[8][8];
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jPanel3 = new javax.swing.JPanel();
        scoreField1 = new javax.swing.JTextField();
        scoreField2 = new javax.swing.JTextField();
        score1Field = new javax.swing.JTextField();
        score2Field = new javax.swing.JTextField();
        exitButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        tile_0_0 = new javax.swing.JButton();
        tile_0_1 = new javax.swing.JButton();
        tile_0_7 = new javax.swing.JButton();
        tile_0_6 = new javax.swing.JButton();
        tile_0_5 = new javax.swing.JButton();
        tile_0_4 = new javax.swing.JButton();
        tile_0_3 = new javax.swing.JButton();
        tile_0_2 = new javax.swing.JButton();
        tile_1_0 = new javax.swing.JButton();
        tile_1_1 = new javax.swing.JButton();
        tile_1_2 = new javax.swing.JButton();
        tile_1_3 = new javax.swing.JButton();
        tile_1_4 = new javax.swing.JButton();
        tile_1_5 = new javax.swing.JButton();
        tile_1_6 = new javax.swing.JButton();
        tile_1_7 = new javax.swing.JButton();
        tile_2_7 = new javax.swing.JButton();
        tile_2_6 = new javax.swing.JButton();
        tile_2_5 = new javax.swing.JButton();
        tile_2_4 = new javax.swing.JButton();
        tile_2_3 = new javax.swing.JButton();
        tile_2_2 = new javax.swing.JButton();
        tile_2_1 = new javax.swing.JButton();
        tile_2_0 = new javax.swing.JButton();
        tile_3_5 = new javax.swing.JButton();
        tile_3_7 = new javax.swing.JButton();
        tile_3_6 = new javax.swing.JButton();
        tile_3_0 = new javax.swing.JButton();
        tile_3_2 = new javax.swing.JButton();
        tile_3_4 = new javax.swing.JButton();
        tile_3_3 = new javax.swing.JButton();
        tile_3_1 = new javax.swing.JButton();
        tile_4_0 = new javax.swing.JButton();
        tile_4_2 = new javax.swing.JButton();
        tile_4_6 = new javax.swing.JButton();
        tile_4_5 = new javax.swing.JButton();
        tile_4_1 = new javax.swing.JButton();
        tile_4_3 = new javax.swing.JButton();
        tile_4_7 = new javax.swing.JButton();
        tile_4_4 = new javax.swing.JButton();
        tile_5_0 = new javax.swing.JButton();
        tile_5_6 = new javax.swing.JButton();
        tile_5_3 = new javax.swing.JButton();
        tile_5_7 = new javax.swing.JButton();
        tile_5_4 = new javax.swing.JButton();
        tile_5_1 = new javax.swing.JButton();
        tile_5_2 = new javax.swing.JButton();
        tile_5_5 = new javax.swing.JButton();
        tile_6_1 = new javax.swing.JButton();
        tile_6_6 = new javax.swing.JButton();
        tile_6_0 = new javax.swing.JButton();
        tile_6_4 = new javax.swing.JButton();
        tile_6_2 = new javax.swing.JButton();
        tile_6_5 = new javax.swing.JButton();
        tile_6_3 = new javax.swing.JButton();
        tile_6_7 = new javax.swing.JButton();
        tile_7_1 = new javax.swing.JButton();
        tile_7_6 = new javax.swing.JButton();
        tile_7_5 = new javax.swing.JButton();
        tile_7_3 = new javax.swing.JButton();
        tile_7_4 = new javax.swing.JButton();
        tile_7_7 = new javax.swing.JButton();
        tile_7_0 = new javax.swing.JButton();
        tile_7_2 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        jButton1.setText("jButton1");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        scoreField1.setEditable(false);
        scoreField1.setBackground(new java.awt.Color(0, 0, 0));
        scoreField1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        scoreField1.setForeground(new java.awt.Color(255, 255, 255));
        scoreField1.setText("Your Score");
        scoreField1.setBorder(null);
        scoreField1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        scoreField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreField1ActionPerformed(evt);
            }
        });

        scoreField2.setEditable(false);
        scoreField2.setBackground(new java.awt.Color(0, 0, 0));
        scoreField2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        scoreField2.setForeground(new java.awt.Color(255, 255, 255));
        scoreField2.setText("Computer Score");
        scoreField2.setBorder(null);
        scoreField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreField2ActionPerformed(evt);
            }
        });

        score1Field.setEditable(false);
        score1Field.setBackground(new java.awt.Color(0, 0, 0));
        score1Field.setForeground(new java.awt.Color(255, 255, 255));
        score1Field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        score1Field.setText("score1");
        score1Field.setBorder(null);
        score1Field.setMargin(new java.awt.Insets(0, 0, 0, 0));
        score1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                score1FieldActionPerformed(evt);
            }
        });

        score2Field.setEditable(false);
        score2Field.setBackground(new java.awt.Color(0, 0, 0));
        score2Field.setForeground(new java.awt.Color(255, 255, 255));
        score2Field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        score2Field.setText("score2");
        score2Field.setBorder(null);
        score2Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                score2FieldActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(0, 0, 0));
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("Exit");
        exitButton.setBorder(null);

        resetButton.setBackground(new java.awt.Color(0, 0, 0));
        resetButton.setForeground(new java.awt.Color(255, 255, 255));
        resetButton.setText("Reset");
        resetButton.setBorder(null);

        tile_0_0.setBackground(new java.awt.Color(47, 173, 81));
        tile_0_0.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_0_0.setBorder(null);
        tile_0_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_0_0ActionPerformed(evt);
            }
        });

        tile_0_1.setBackground(new java.awt.Color(47, 173, 81));
        tile_0_1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        tile_0_1.setBorder(null);
        tile_0_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_0_1ActionPerformed(evt);
            }
        });

        tile_0_7.setBackground(new java.awt.Color(47, 173, 81));
        tile_0_7.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_0_7.setBorder(null);
        tile_0_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_0_7ActionPerformed(evt);
            }
        });

        tile_0_6.setBackground(new java.awt.Color(47, 173, 81));
        tile_0_6.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_0_6.setBorder(null);
        tile_0_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_0_6ActionPerformed(evt);
            }
        });

        tile_0_5.setBackground(new java.awt.Color(47, 173, 81));
        tile_0_5.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_0_5.setBorder(null);
        tile_0_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_0_5ActionPerformed(evt);
            }
        });

        tile_0_4.setBackground(new java.awt.Color(47, 173, 81));
        tile_0_4.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_0_4.setBorder(null);
        tile_0_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_0_4ActionPerformed(evt);
            }
        });

        tile_0_3.setBackground(new java.awt.Color(47, 173, 81));
        tile_0_3.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_0_3.setBorder(null);
        tile_0_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_0_3ActionPerformed(evt);
            }
        });

        tile_0_2.setBackground(new java.awt.Color(47, 173, 81));
        tile_0_2.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_0_2.setBorder(null);
        tile_0_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_0_2ActionPerformed(evt);
            }
        });

        tile_1_0.setBackground(new java.awt.Color(47, 173, 81));
        tile_1_0.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_1_0.setBorder(null);
        tile_1_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_1_0ActionPerformed(evt);
            }
        });

        tile_1_1.setBackground(new java.awt.Color(47, 173, 81));
        tile_1_1.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_1_1.setBorder(null);
        tile_1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_1_1ActionPerformed(evt);
            }
        });

        tile_1_2.setBackground(new java.awt.Color(47, 173, 81));
        tile_1_2.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_1_2.setBorder(null);
        tile_1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_1_2ActionPerformed(evt);
            }
        });

        tile_1_3.setBackground(new java.awt.Color(47, 173, 81));
        tile_1_3.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_1_3.setBorder(null);
        tile_1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_1_3ActionPerformed(evt);
            }
        });

        tile_1_4.setBackground(new java.awt.Color(47, 173, 81));
        tile_1_4.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_1_4.setBorder(null);
        tile_1_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_1_4ActionPerformed(evt);
            }
        });

        tile_1_5.setBackground(new java.awt.Color(47, 173, 81));
        tile_1_5.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_1_5.setBorder(null);
        tile_1_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_1_5ActionPerformed(evt);
            }
        });

        tile_1_6.setBackground(new java.awt.Color(47, 173, 81));
        tile_1_6.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_1_6.setBorder(null);
        tile_1_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_1_6ActionPerformed(evt);
            }
        });

        tile_1_7.setBackground(new java.awt.Color(47, 173, 81));
        tile_1_7.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_1_7.setBorder(null);
        tile_1_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_1_7ActionPerformed(evt);
            }
        });

        tile_2_7.setBackground(new java.awt.Color(47, 173, 81));
        tile_2_7.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_2_7.setBorder(null);
        tile_2_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_2_7ActionPerformed(evt);
            }
        });

        tile_2_6.setBackground(new java.awt.Color(47, 173, 81));
        tile_2_6.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_2_6.setBorder(null);
        tile_2_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_2_6ActionPerformed(evt);
            }
        });

        tile_2_5.setBackground(new java.awt.Color(47, 173, 81));
        tile_2_5.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_2_5.setBorder(null);
        tile_2_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_2_5ActionPerformed(evt);
            }
        });

        tile_2_4.setBackground(new java.awt.Color(47, 173, 81));
        tile_2_4.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_2_4.setBorder(null);
        tile_2_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_2_4ActionPerformed(evt);
            }
        });

        tile_2_3.setBackground(new java.awt.Color(47, 173, 81));
        tile_2_3.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_2_3.setBorder(null);
        tile_2_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_2_3ActionPerformed(evt);
            }
        });

        tile_2_2.setBackground(new java.awt.Color(47, 173, 81));
        tile_2_2.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_2_2.setBorder(null);
        tile_2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_2_2ActionPerformed(evt);
            }
        });

        tile_2_1.setBackground(new java.awt.Color(47, 173, 81));
        tile_2_1.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_2_1.setBorder(null);
        tile_2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_2_1ActionPerformed(evt);
            }
        });

        tile_2_0.setBackground(new java.awt.Color(47, 173, 81));
        tile_2_0.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_2_0.setBorder(null);
        tile_2_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_2_0ActionPerformed(evt);
            }
        });

        tile_3_5.setBackground(new java.awt.Color(47, 173, 81));
        tile_3_5.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_3_5.setBorder(null);
        tile_3_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_3_5ActionPerformed(evt);
            }
        });

        tile_3_7.setBackground(new java.awt.Color(47, 173, 81));
        tile_3_7.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_3_7.setBorder(null);
        tile_3_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_3_7ActionPerformed(evt);
            }
        });

        tile_3_6.setBackground(new java.awt.Color(47, 173, 81));
        tile_3_6.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_3_6.setBorder(null);
        tile_3_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_3_6ActionPerformed(evt);
            }
        });

        tile_3_0.setBackground(new java.awt.Color(47, 173, 81));
        tile_3_0.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_3_0.setBorder(null);
        tile_3_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_3_0ActionPerformed(evt);
            }
        });

        tile_3_2.setBackground(new java.awt.Color(47, 173, 81));
        tile_3_2.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_3_2.setBorder(null);
        tile_3_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_3_2ActionPerformed(evt);
            }
        });

        tile_3_4.setBackground(new java.awt.Color(47, 173, 81));
        tile_3_4.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_3_4.setText("●");
        tile_3_4.setBorder(null);
        tile_3_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_3_4ActionPerformed(evt);
            }
        });

        tile_3_3.setBackground(new java.awt.Color(47, 173, 81));
        tile_3_3.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_3_3.setForeground(new java.awt.Color(255, 255, 255));
        tile_3_3.setText("●");
        tile_3_3.setAlignmentY(0.0F);
        tile_3_3.setBorder(null);
        tile_3_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_3_3ActionPerformed(evt);
            }
        });

        tile_3_1.setBackground(new java.awt.Color(47, 173, 81));
        tile_3_1.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_3_1.setBorder(null);
        tile_3_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_3_1ActionPerformed(evt);
            }
        });

        tile_4_0.setBackground(new java.awt.Color(47, 173, 81));
        tile_4_0.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_4_0.setBorder(null);
        tile_4_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_4_0ActionPerformed(evt);
            }
        });

        tile_4_2.setBackground(new java.awt.Color(47, 173, 81));
        tile_4_2.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_4_2.setBorder(null);
        tile_4_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_4_2ActionPerformed(evt);
            }
        });

        tile_4_6.setBackground(new java.awt.Color(47, 173, 81));
        tile_4_6.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_4_6.setBorder(null);
        tile_4_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_4_6ActionPerformed(evt);
            }
        });

        tile_4_5.setBackground(new java.awt.Color(47, 173, 81));
        tile_4_5.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_4_5.setBorder(null);
        tile_4_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_4_5ActionPerformed(evt);
            }
        });

        tile_4_1.setBackground(new java.awt.Color(47, 173, 81));
        tile_4_1.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_4_1.setBorder(null);
        tile_4_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_4_1ActionPerformed(evt);
            }
        });

        tile_4_3.setBackground(new java.awt.Color(47, 173, 81));
        tile_4_3.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_4_3.setText("●");
        tile_4_3.setBorder(null);
        tile_4_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_4_3ActionPerformed(evt);
            }
        });

        tile_4_7.setBackground(new java.awt.Color(47, 173, 81));
        tile_4_7.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_4_7.setBorder(null);
        tile_4_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_4_7ActionPerformed(evt);
            }
        });

        tile_4_4.setBackground(new java.awt.Color(47, 173, 81));
        tile_4_4.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_4_4.setForeground(new java.awt.Color(255, 255, 255));
        tile_4_4.setText("●");
        tile_4_4.setBorder(null);
        tile_4_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_4_4ActionPerformed(evt);
            }
        });

        tile_5_0.setBackground(new java.awt.Color(47, 173, 81));
        tile_5_0.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_5_0.setBorder(null);
        tile_5_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_5_0ActionPerformed(evt);
            }
        });

        tile_5_6.setBackground(new java.awt.Color(47, 173, 81));
        tile_5_6.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_5_6.setBorder(null);
        tile_5_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_5_6ActionPerformed(evt);
            }
        });

        tile_5_3.setBackground(new java.awt.Color(47, 173, 81));
        tile_5_3.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_5_3.setBorder(null);
        tile_5_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_5_3ActionPerformed(evt);
            }
        });

        tile_5_7.setBackground(new java.awt.Color(47, 173, 81));
        tile_5_7.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_5_7.setBorder(null);
        tile_5_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_5_7ActionPerformed(evt);
            }
        });

        tile_5_4.setBackground(new java.awt.Color(47, 173, 81));
        tile_5_4.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_5_4.setBorder(null);
        tile_5_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_5_4ActionPerformed(evt);
            }
        });

        tile_5_1.setBackground(new java.awt.Color(47, 173, 81));
        tile_5_1.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_5_1.setBorder(null);
        tile_5_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_5_1ActionPerformed(evt);
            }
        });

        tile_5_2.setBackground(new java.awt.Color(47, 173, 81));
        tile_5_2.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_5_2.setBorder(null);
        tile_5_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_5_2ActionPerformed(evt);
            }
        });

        tile_5_5.setBackground(new java.awt.Color(47, 173, 81));
        tile_5_5.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_5_5.setBorder(null);
        tile_5_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_5_5ActionPerformed(evt);
            }
        });

        tile_6_1.setBackground(new java.awt.Color(47, 173, 81));
        tile_6_1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        tile_6_1.setBorder(null);
        tile_6_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_6_1ActionPerformed(evt);
            }
        });

        tile_6_6.setBackground(new java.awt.Color(47, 173, 81));
        tile_6_6.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_6_6.setBorder(null);
        tile_6_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_6_6ActionPerformed(evt);
            }
        });

        tile_6_0.setBackground(new java.awt.Color(47, 173, 81));
        tile_6_0.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_6_0.setBorder(null);
        tile_6_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_6_0ActionPerformed(evt);
            }
        });

        tile_6_4.setBackground(new java.awt.Color(47, 173, 81));
        tile_6_4.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_6_4.setBorder(null);
        tile_6_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_6_4ActionPerformed(evt);
            }
        });

        tile_6_2.setBackground(new java.awt.Color(47, 173, 81));
        tile_6_2.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_6_2.setBorder(null);
        tile_6_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_6_2ActionPerformed(evt);
            }
        });

        tile_6_5.setBackground(new java.awt.Color(47, 173, 81));
        tile_6_5.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_6_5.setBorder(null);
        tile_6_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_6_5ActionPerformed(evt);
            }
        });

        tile_6_3.setBackground(new java.awt.Color(47, 173, 81));
        tile_6_3.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_6_3.setBorder(null);
        tile_6_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_6_3ActionPerformed(evt);
            }
        });

        tile_6_7.setBackground(new java.awt.Color(47, 173, 81));
        tile_6_7.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_6_7.setBorder(null);
        tile_6_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_6_7ActionPerformed(evt);
            }
        });

        tile_7_1.setBackground(new java.awt.Color(47, 173, 81));
        tile_7_1.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_7_1.setBorder(null);
        tile_7_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_7_1ActionPerformed(evt);
            }
        });

        tile_7_6.setBackground(new java.awt.Color(47, 173, 81));
        tile_7_6.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_7_6.setBorder(null);
        tile_7_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_7_6ActionPerformed(evt);
            }
        });

        tile_7_5.setBackground(new java.awt.Color(47, 173, 81));
        tile_7_5.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_7_5.setBorder(null);
        tile_7_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_7_5ActionPerformed(evt);
            }
        });

        tile_7_3.setBackground(new java.awt.Color(47, 173, 81));
        tile_7_3.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_7_3.setBorder(null);
        tile_7_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_7_3ActionPerformed(evt);
            }
        });

        tile_7_4.setBackground(new java.awt.Color(47, 173, 81));
        tile_7_4.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_7_4.setBorder(null);
        tile_7_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_7_4ActionPerformed(evt);
            }
        });

        tile_7_7.setBackground(new java.awt.Color(47, 173, 81));
        tile_7_7.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_7_7.setBorder(null);
        tile_7_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_7_7ActionPerformed(evt);
            }
        });

        tile_7_0.setBackground(new java.awt.Color(47, 173, 81));
        tile_7_0.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_7_0.setBorder(null);
        tile_7_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_7_0ActionPerformed(evt);
            }
        });

        tile_7_2.setBackground(new java.awt.Color(47, 173, 81));
        tile_7_2.setFont(new java.awt.Font("Arial", 0, 72)); // NOI18N
        tile_7_2.setBorder(null);
        tile_7_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tile_7_2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scoreField1)
                    .addComponent(scoreField2))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(score1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(resetButton, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(score2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tile_0_0, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_0_1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_0_2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_0_3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_0_4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_0_5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_0_6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_0_7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tile_1_0, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_1_7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tile_2_0, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_2_5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_2_6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_2_7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tile_3_0, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_3_4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_3_5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_3_6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_3_7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tile_4_0, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_4_4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_4_5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_4_6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_4_7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tile_5_0, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_5_2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_5_3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_5_4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_5_5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_5_6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_5_7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tile_6_0, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_6_1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_6_2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_6_3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_6_4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_6_5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_6_6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_6_7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tile_7_0, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_7_1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_7_2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_7_3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_7_4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_7_5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_7_6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tile_7_7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scoreField1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(score1Field)
                    .addComponent(resetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tile_0_7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_0_6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_0_5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_0_4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_0_3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_0_2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_0_1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_0_0, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tile_1_7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_1_0, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tile_2_7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_2_6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_2_5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_2_0, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tile_3_7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_3_6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_3_5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_3_4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_3_0, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tile_4_7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_4_6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_4_5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_4_4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_4_0, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tile_5_7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_5_6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_5_5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_5_4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_5_3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_5_2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_5_0, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tile_6_7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_6_6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_6_5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_6_4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_6_3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_6_2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_6_1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_6_0, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tile_7_7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_7_6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_7_5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_7_4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_7_3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_7_2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_7_1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tile_7_0, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scoreField2)
                    .addComponent(score2Field)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        scoreField1.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scoreField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scoreField2ActionPerformed

    private void scoreField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scoreField1ActionPerformed

    private void score1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_score1FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_score1FieldActionPerformed

    private void score2FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_score2FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_score2FieldActionPerformed

    private void tile_0_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_0_0ActionPerformed
        // TODO add your handling code here:
        tile_0_0.setText("●");
        if (tile_0_0.getForeground().getRGB() == -1) {
            arrayBoard[0][0] = 1;
        }
        else {
            arrayBoard[0][0] = 0;
        }
        boardList[0][0] = tile_0_0;
    }//GEN-LAST:event_tile_0_0ActionPerformed

    private void tile_0_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_0_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_0_1ActionPerformed

    private void tile_0_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_0_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_0_2ActionPerformed

    private void tile_0_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_0_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_0_3ActionPerformed

    private void tile_0_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_0_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_0_4ActionPerformed

    private void tile_0_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_0_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_0_5ActionPerformed

    private void tile_0_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_0_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_0_6ActionPerformed

    private void tile_0_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_0_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_0_7ActionPerformed

    private void tile_1_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_1_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_1_0ActionPerformed

    private void tile_1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_1_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_1_1ActionPerformed

    private void tile_1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_1_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_1_2ActionPerformed

    private void tile_1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_1_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_1_3ActionPerformed

    private void tile_1_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_1_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_1_4ActionPerformed

    private void tile_1_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_1_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_1_5ActionPerformed

    private void tile_1_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_1_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_1_6ActionPerformed

    private void tile_1_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_1_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_1_7ActionPerformed

    private void tile_2_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_2_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_2_0ActionPerformed

    private void tile_2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_2_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_2_1ActionPerformed

    private void tile_2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_2_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_2_2ActionPerformed

    private void tile_2_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_2_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_2_3ActionPerformed

    private void tile_2_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_2_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_2_4ActionPerformed

    private void tile_2_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_2_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_2_5ActionPerformed

    private void tile_2_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_2_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_2_6ActionPerformed

    private void tile_2_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_2_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_2_7ActionPerformed

    private void tile_3_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_3_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_3_0ActionPerformed

    private void tile_3_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_3_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_3_1ActionPerformed

    private void tile_3_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_3_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_3_2ActionPerformed

    private void tile_3_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_3_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_3_3ActionPerformed

    private void tile_3_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_3_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_3_4ActionPerformed

    private void tile_3_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_3_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_3_5ActionPerformed

    private void tile_3_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_3_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_3_6ActionPerformed

    private void tile_3_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_3_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_3_7ActionPerformed

    private void tile_4_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_4_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_4_0ActionPerformed

    private void tile_4_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_4_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_4_1ActionPerformed

    private void tile_4_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_4_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_4_2ActionPerformed

    private void tile_4_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_4_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_4_3ActionPerformed

    private void tile_4_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_4_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_4_4ActionPerformed

    private void tile_4_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_4_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_4_5ActionPerformed

    private void tile_4_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_4_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_4_6ActionPerformed

    private void tile_4_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_4_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_4_7ActionPerformed

    private void tile_5_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_5_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_5_0ActionPerformed

    private void tile_5_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_5_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_5_1ActionPerformed

    private void tile_5_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_5_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_5_2ActionPerformed

    private void tile_5_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_5_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_5_3ActionPerformed

    private void tile_5_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_5_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_5_4ActionPerformed

    private void tile_5_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_5_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_5_5ActionPerformed

    private void tile_5_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_5_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_5_6ActionPerformed

    private void tile_5_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_5_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_5_7ActionPerformed

    private void tile_6_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_6_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_6_0ActionPerformed

    private void tile_6_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_6_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_6_1ActionPerformed

    private void tile_6_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_6_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_6_2ActionPerformed

    private void tile_6_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_6_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_6_3ActionPerformed

    private void tile_6_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_6_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_6_4ActionPerformed

    private void tile_6_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_6_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_6_5ActionPerformed

    private void tile_6_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_6_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_6_6ActionPerformed

    private void tile_6_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_6_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_6_7ActionPerformed

    private void tile_7_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_7_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_7_0ActionPerformed

    private void tile_7_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_7_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_7_1ActionPerformed

    private void tile_7_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_7_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_7_2ActionPerformed

    private void tile_7_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_7_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_7_3ActionPerformed

    private void tile_7_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_7_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_7_4ActionPerformed

    private void tile_7_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_7_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_7_5ActionPerformed

    private void tile_7_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_7_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_7_6ActionPerformed

    private void tile_7_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tile_7_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tile_7_7ActionPerformed
    
    private void myInitComponents() {
        //any necessary adjustments to GUI go here
        
    }
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        //GUI Setup
        ReversiBoard guiBoard = new ReversiBoard();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                guiBoard.setVisible(true);
            }
        });
        
        //initialize variables
        boardList = guiBoard.storeBoard();
        //transfers buttons into array in ReversiBoard class
        arrayBoard = guiBoard.storeToArrayBoard(boardList);
        boolean notWin = true;
        
        //updates GUI portion using array
        guiBoard.updateBoard(boardList);
        
        
        //all below is testing
        //intializing numerical board
        
        //test returnMoves
        ArrayList<int[]> legalMoves = new ArrayList<int[]>();
        legalMoves = guiBoard.returnMoves(arrayBoard);
        guiBoard.showLegal(legalMoves,boardList);
        
        
        /*in each actionListener:
        - setText in boardList object to circle
        */
        
        //template for actionListeners
        boardList[0][0].setText("●");

        //!!! NEED A FUNCTION TO SCAN BOARD FROM GUI AND UPDATE boardList AND arrayBoard
        //flow: button pressed > gui updated > scanner method run > 
        
        //test actionListeners
        for (int i = 0; i < 8; i++) {
            for (int k = 0; k < 8; k++) {
                System.out.print(arrayBoard[i][k]);
            }
            System.out.println();
        }
        
        while(notWin) {
            //flips who moves
            //after flipping moves, changes the foreground property for all legal moves to be the color of the current player
            
            
            //checks to see when to stop game: if neither player has legal moves (eg. use legalMove function for both black and white
            /*
                if (returnMoves(arrayBoard).isEmpty() && returnMoves(newArrayBoard).isEmpty() {
                    notWin = false;
                }
                ***newArrayBoard is the board when flipped to opponent's end, use Aidan's reverse board function for this
            */
        }
    }
    
    //GUI functions
    //takes index values and updates them onto board, update GUI
    public void updateBoard(JButton[][] board) {
        tile_0_0 = board[0][1];
        tile_0_1 = board[0][1];
        tile_0_2 = board[0][2];
        tile_0_3 = board[0][3];
        tile_0_4 = board[0][4];
        tile_0_5 = board[0][5];
        tile_0_6 = board[0][6];
        tile_0_7 = board[0][7];
        //1st row
        tile_1_0 = board[1][0];
        tile_1_1 = board[1][1];
        tile_1_2 = board[1][2];
        tile_1_3 = board[1][3];
        tile_1_4 = board[1][4];
        tile_1_5 = board[1][5];
        tile_1_6 = board[1][6];
        tile_1_7 = board[1][7];
        //2nd row
        tile_2_0 = board[2][0];
        tile_2_1 = board[2][1];
        tile_2_2 = board[2][2];
        tile_2_3 = board[2][3];
        tile_2_4 = board[2][4];
        tile_2_5 = board[2][5];
        tile_2_6 = board[2][6];
        tile_2_7 = board[2][7];
        //3rd row
        tile_3_0 = board[3][0];
        tile_3_1 = board[3][1];
        tile_3_2 = board[3][2];
        tile_3_3 = board[3][3];
        tile_3_4 = board[3][4];
        tile_3_5 = board[3][5];
        tile_3_6 = board[3][6];
        tile_3_7 = board[3][7];
        //4th row
        tile_4_0 = board[4][0];
        tile_4_1 = board[4][1];
        tile_4_2 = board[4][2];
        tile_4_3 = board[4][3];
        tile_4_4 = board[4][4];
        tile_4_5 = board[4][5];
        tile_4_6 = board[4][6];
        tile_4_7 = board[4][7];
        //5th row
        tile_5_0 = board[5][0];
        tile_5_1 = board[5][1];
        tile_5_2 = board[5][2];
        tile_5_3 = board[5][3];
        tile_5_4 = board[5][4];
        tile_5_5 = board[5][5];
        tile_5_6 = board[5][6];
        tile_5_7 = board[5][7];
        //6th row
        tile_6_0 = board[6][0];
        tile_6_1 = board[6][1];
        tile_6_2 = board[6][2];
        tile_6_3 = board[6][3];
        tile_6_4 = board[6][4];
        tile_6_5 = board[6][5];
        tile_6_6 = board[6][6];
        tile_6_7 = board[6][7];
        //7th row
        tile_7_0 = board[7][0];
        tile_7_1 = board[7][1];
        tile_7_2 = board[7][2];
        tile_7_3 = board[7][3];
        tile_7_4 = board[7][4];
        tile_7_5 = board[7][5];
        tile_7_6 = board[7][6];
        tile_7_7 = board[7][7];
        revalidate();
        repaint();
    }
    
    //clears board and places starting pieces; resets scores
    public void resetBoard() {
        
    }
    
    //swap between black and white pieces, used for makeMove
    
    //places a piece on 
    public void makeMove() {
        
    }
    
    public void showLegal(ArrayList<int[]> moves, JButton[][] board) {
        JButton[][] newBoard = board; //needed to update board
        int[] compareArray = new int[2]; //gets the coordinate array stored in moves eg. [2,2] matches with tile_2_2
        int xPos = 0; //first coordinate stored in compareArray
        int yPos = 0; //second coordinate stored in compareArray
        disableMoves(newBoard); //disables every button on the board
        for (int i = 0; i < moves.size(); i++) {
            compareArray = moves.get(i);
            xPos = compareArray[0];
            yPos = compareArray[1];
            newBoard[xPos][yPos].setBackground(new Color(0,153,153));
            newBoard[xPos][yPos].setEnabled(true); //reenables moves
        }
        updateBoard(newBoard);
    }
    
    public void resetLegal (JButton[][] board) { //makes all buttons green again
        JButton[][] newBoard = board;
        for (int i = 0; i < 8; i++) {
            for (int k = 0; k < 8; k++) {
                newBoard[i][k].setBackground(new Color(47,173,81));
            }
        }
        updateBoard(newBoard);
    }

    public void enableMoves(JButton[][] board) { //enables all buttons on board, used as a soft reset between moves
        JButton[][] newBoard = board; //needed to update board
        for (int i = 0; i < 8; i++) {
            for (int k = 0; k < 8; k++) {
                    newBoard[i][k].setEnabled(true);
            }
        }
        updateBoard(newBoard);
    }

    public void disableMoves(JButton[][] board) { //disables all buttons on board, used in tandem with showLegal, which will reenable only legal moves
        JButton[][] newBoard = board; //needed to update board
        int[][] arrayBoard = storeToArrayBoard(newBoard);
        for (int i = 0; i < 8; i++) {
            for (int k = 0; k < 8; k++) {
                if (arrayBoard[i][k] == 0) //buttons with pieces will still be enabled
                    newBoard[i][k].setEnabled(false); //disables buttons
            }
        }
        updateBoard(newBoard);
    }
    
    //logic functions
    
    public JButton[][] storeBoard() { //stores the board in 
        JButton[][] board = new JButton[8][8];
        //0th row
        board[0][0] = tile_0_0;
        board[0][1] = tile_0_1;
        board[0][2] = tile_0_2;
        board[0][3] = tile_0_3;
        board[0][4] = tile_0_4;
        board[0][5] = tile_0_5;
        board[0][6] = tile_0_6;
        board[0][7] = tile_0_7;
        //1st row
        board[1][0] = tile_1_0;
        board[1][1] = tile_1_1;
        board[1][2] = tile_1_2;
        board[1][3] = tile_1_3;
        board[1][4] = tile_1_4;
        board[1][5] = tile_1_5;
        board[1][6] = tile_1_6;
        board[1][7] = tile_1_7;
        //2nd row
        board[2][0] = tile_2_0;
        board[2][1] = tile_2_1;
        board[2][2] = tile_2_2;
        board[2][3] = tile_2_3;
        board[2][4] = tile_2_4;
        board[2][5] = tile_2_5;
        board[2][6] = tile_2_6;
        board[2][7] = tile_2_7;
        //3rd row
        board[3][0] = tile_3_0;
        board[3][1] = tile_3_1;
        board[3][2] = tile_3_2;
        board[3][3] = tile_3_3;
        board[3][4] = tile_3_4;
        board[3][5] = tile_3_5;
        board[3][6] = tile_3_6;
        board[3][7] = tile_3_7;
        //4th row
        board[4][0] = tile_4_0;
        board[4][1] = tile_4_1;
        board[4][2] = tile_4_2;
        board[4][3] = tile_4_3;
        board[4][4] = tile_4_4;
        board[4][5] = tile_4_5;
        board[4][6] = tile_4_6;
        board[4][7] = tile_4_7;
        //5th row
        board[5][0] = tile_5_0;
        board[5][1] = tile_5_1;
        board[5][2] = tile_5_2;
        board[5][3] = tile_5_3;
        board[5][4] = tile_5_4;
        board[5][5] = tile_5_5;
        board[5][6] = tile_5_6;
        board[5][7] = tile_5_7;
        //6th row
        board[6][0] = tile_6_0;
        board[6][1] = tile_6_1;
        board[6][2] = tile_6_2;
        board[6][3] = tile_6_3;
        board[6][4] = tile_6_4;
        board[6][5] = tile_6_5;
        board[6][6] = tile_6_6;
        board[6][7] = tile_6_7;
        //7th row
        board[7][0] = tile_7_0;
        board[7][1] = tile_7_1;
        board[7][2] = tile_7_2;
        board[7][3] = tile_7_3;
        board[7][4] = tile_7_4;
        board[7][5] = tile_7_5;
        board[7][6] = tile_7_6;
        board[7][7] = tile_7_7;
        return board;
    }  
    
    public int[][] storeToArrayBoard(JButton[][] board) {
        int[][] arrayBoard = new int[8][8];
        for (int i = 0; i < 8; i++) {
            for (int k = 0; k < 8; k++) {
                
                if (board[i][k].getText().isEmpty()) { //value for EMPTY tile
                    arrayBoard[i][k] = 0;
                }
                else if (board[i][k].getForeground().getRGB() == -1) { //RGB value for BLACK pieces
                    arrayBoard[i][k] = 1;
                }
                else { //WHITE pieces
                    arrayBoard[i][k] = 2;
                }
            }
        }
        return arrayBoard;
    }
    
    public JButton[][] storeFromArrayBoard(int[][] board) {
        JButton[][] buttonBoard = new JButton[8][8];
        for (int i = 0; i < 8; i++) {
            for (int k = 0; k < 8; k++) {
                if (board[i][k] == 1) { //set value for BLACK pieces
                    buttonBoard[i][k].setForeground(Color.BLACK);
                }
                else { //WHITE pieces
                    buttonBoard[i][k].setForeground(Color.WHITE);
                }
            }
        }
        return buttonBoard;
    }
    
    //Ellen implementations
    
    public boolean CanFlipTile(int wx, int wy, int bx, int by, int[][] hi) {//"place" is the new tile of color 2, "flip" is the old tile of color 1
	int sum = bx+by-wx-wy;
	//basically draws lines to figure out whether if someone is placing it, the new tile can flip the original tile 
	//0 = empty, 1= black, 2=white
		
	//this perspective is that I'm the white tile, looking to flip a black tile
	if (sum==-2) { 
            while (bx<8 && by<8) {
                bx++;
		by++;
		if (hi[bx][by]==0) {return false;} //empty; therefore I cannot flip the tile
                // if (b.getColor(flipx,flipy,b)){return false;}
		else if (hi[bx][by]==2) {return true;}
		}
	}
		
	else if (sum==2) {
            while (0<=bx && 0<=by) {
                bx--;
                by--;
                if (hi[bx][by]==0)  { return false;} //if tile is empty, then there's no way to flip so just return false
                else if (hi[bx][by]==2) {return true;} //
            }
	}
		
	else if (sum==-1) {
            if (bx==wx) {
                while (0<=by) {
                    by--;
                    if (hi[bx][by]==0)  { return false;}
                    else if (hi[bx][by]==2)  { return true;}
		}
            }
            else {
		while (0<=bx) {
                    bx--;
                    if (hi[bx][by]==0)  { return false;}
                    else if (hi[bx][by]==2)  { return true;}
		}
            }
	}
	else if (sum==1) {
            if (bx==wx) {
		while (by<8) {
                    by++;
                    if (hi[bx][by]==0)  { return false;}
                    else if (hi[bx][by]==2)  { return true;}
		}
            }
            else {
		while (bx<8) {
                    bx++;
                    if (hi[bx][by]==0)  { return false;}
                    else if (hi[bx][by]==2)  { return true;}
		}
            }
	}
	else {//sum=0
            if (bx>wx) {
		while (bx<8 && 0<=by) {
                    bx++;
                    by--;
                    if (hi[bx][by]==0)  { return false;}
                    else if (hi[bx][by]==2)  { return true;}
		}
            }
            else { 
		while (by<8 && 0<=bx ) {
                    bx--;
                    by++;
                    if (hi[bx][by]==0)  { return false;}
                    else if (hi[bx][by]==2)  { return true;}
		}
            }
	}
		return false;
    }
	
    public ArrayList<int[]> returnMoves(int[][] board) {//ARRAY OF ARRAYS
        //return possible moves for player2 (who is playing with 2 (i.e. white))
        //rules: empty, adjacent and must flip when placed


        ArrayList<int[]> available = new ArrayList<int[]>();
        //so it should return something like {{1,2}, {2,2}, {3,4}} so each element is an array that represents a single tile. 
        //In total, it represents all possible tiles during a move
        int[][] COPY = new int[8][8];
        int index = 0;

        for (int i=0; i<8; i++) {
            for (int j=0; j<8; j++) {
                COPY[i][j] = board[i][j];
        }}

        for (int i=0; i<8; i++) {
            for (int j=0; j<8; j++) {
                if (COPY[i][j]==1) {//if opponent had placed a piece on this cell

                    //find adjacent empty squares
                    int r= i-1; //super long code
                    int c= j-1; //basically if it's one of the four adjacent squares

                    for (int row = r; row<r+3; row++) {
                        for (int col = c; col<c+3; col++) {
                            if (0<= row && row<8 && 0<= col && col<8 && !(row==i && col==j)) {
                                if (COPY[row][col]==0 &&  CanFlipTile(row,col,i,j,board)) {//if there exists an empty adjacent tile
                                    int[] Point = new int[2];
                                    Point[0]=row;
                                    Point[1]=col;
                                    available.add(index, Point);
                                    index++;
                                }
                            }
                        }
                    }
                }
            }
        }
        return available;
    }
   
    //Aidan implementations
    
    public static int[][] makeBoardCopy(int[][] oldBoard){ //creats a duplicate board with a seperate memory address but the same data
        int[][] boardCopy = new int[8][8]; 
        for (int i = 0; i < 8; i++){ 
            for (int c = 0; c < 8; c++){ 
                boardCopy[i][c] = oldBoard[i][c]; //gives boardCopy[i][c] the value of oldBoard[i][c]
            }
        }
      return boardCopy; //returns the identical board that has different memory address
    }

    public static int[][] makeReverseBoard(int[][] oldBoard){ //reverses all of the colors on the board (black --> white && white --> black)
        int[][] boardReverse = makeBoardCopy(oldBoard); //if not in the same class, make sure to modify the static method call
        for (int[] row : boardReverse){ 
            for (int element : row){ 
            if (element == 1){ //black --> white
                element = 2;
            }
            else if (element == 2){ // white --> black
                element = 1;
                }
            }
        }
        return boardReverse; //returns a new board with all of the colors flipped
    }

    public static int getWhiteScore(int[][] board){ //get total white pieces
        int score = 0;
        for (int[] row : board){
            for (int element : row){
                if (element == 2){ //if white, add one to score
                    score++;
                }
            }
        }
        return score;
        //!!!add GUI update and updateboard
    }

    public static int getBlackScore(int[][] board){ //get total black pieces
        int score = 0;
        for (int [] row : board){
            for (int element : row){
            if (element == 1) { //if black, add one ot score
                score++;
                }
            }
        }
        return score;
        //!!!add GUI update and updateboard
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton resetButton;
    public javax.swing.JTextField score1Field;
    public javax.swing.JTextField score2Field;
    private javax.swing.JTextField scoreField1;
    private javax.swing.JTextField scoreField2;
    public javax.swing.JButton tile_0_0;
    public javax.swing.JButton tile_0_1;
    public javax.swing.JButton tile_0_2;
    public javax.swing.JButton tile_0_3;
    public javax.swing.JButton tile_0_4;
    public javax.swing.JButton tile_0_5;
    public javax.swing.JButton tile_0_6;
    public javax.swing.JButton tile_0_7;
    public javax.swing.JButton tile_1_0;
    public javax.swing.JButton tile_1_1;
    public javax.swing.JButton tile_1_2;
    public javax.swing.JButton tile_1_3;
    public javax.swing.JButton tile_1_4;
    public javax.swing.JButton tile_1_5;
    public javax.swing.JButton tile_1_6;
    public javax.swing.JButton tile_1_7;
    public javax.swing.JButton tile_2_0;
    public javax.swing.JButton tile_2_1;
    public javax.swing.JButton tile_2_2;
    public javax.swing.JButton tile_2_3;
    public javax.swing.JButton tile_2_4;
    public javax.swing.JButton tile_2_5;
    public javax.swing.JButton tile_2_6;
    public javax.swing.JButton tile_2_7;
    public javax.swing.JButton tile_3_0;
    public javax.swing.JButton tile_3_1;
    public javax.swing.JButton tile_3_2;
    public javax.swing.JButton tile_3_3;
    public javax.swing.JButton tile_3_4;
    public javax.swing.JButton tile_3_5;
    public javax.swing.JButton tile_3_6;
    public javax.swing.JButton tile_3_7;
    public javax.swing.JButton tile_4_0;
    public javax.swing.JButton tile_4_1;
    public javax.swing.JButton tile_4_2;
    public javax.swing.JButton tile_4_3;
    public javax.swing.JButton tile_4_4;
    public javax.swing.JButton tile_4_5;
    public javax.swing.JButton tile_4_6;
    public javax.swing.JButton tile_4_7;
    public javax.swing.JButton tile_5_0;
    public javax.swing.JButton tile_5_1;
    public javax.swing.JButton tile_5_2;
    public javax.swing.JButton tile_5_3;
    public javax.swing.JButton tile_5_4;
    public javax.swing.JButton tile_5_5;
    public javax.swing.JButton tile_5_6;
    public javax.swing.JButton tile_5_7;
    public javax.swing.JButton tile_6_0;
    public javax.swing.JButton tile_6_1;
    public javax.swing.JButton tile_6_2;
    public javax.swing.JButton tile_6_3;
    public javax.swing.JButton tile_6_4;
    public javax.swing.JButton tile_6_5;
    public javax.swing.JButton tile_6_6;
    public javax.swing.JButton tile_6_7;
    public javax.swing.JButton tile_7_0;
    public javax.swing.JButton tile_7_1;
    public javax.swing.JButton tile_7_2;
    public javax.swing.JButton tile_7_3;
    public javax.swing.JButton tile_7_4;
    public javax.swing.JButton tile_7_5;
    public javax.swing.JButton tile_7_6;
    public javax.swing.JButton tile_7_7;
    // End of variables declaration//GEN-END:variables
}